//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADP.DS.ServiceEdge.Services.EmailService.SmtpEmailServiceProvider.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Diagnostics.CodeAnalysis;
    
     [ExcludeFromCodeCoverage]
    public partial class ServiceEdgeCommonEntities : DbContext
    {
        public ServiceEdgeCommonEntities()
            : base("name=ServiceEdgeCommonEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BadEmailDomain> BadEmailDomains { get; set; }
    }
}
