//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADP.DS.ServiceEdge.Services.EmailService.SmtpEmailServiceProvider.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class BadEmailDomain
    {
        public string Domain { get; set; }
    }
}
